crackman: fix list remote on fresh install

diff --git a/crackman b/crackman
--- a/crackman
+++ b/crackman
@@ -126,14 +126,22 @@ function cm_remove() {
 function list_remote() {
     local name
     local desc
-	wget -O "$CM_TMP_PATH/LISTING" "$MIRROR/LISTING"
+    local listfile
+    listfile="$CM_TMP_PATH/LISTING"
+    cm_doctor
+	wget -O "$listfile" "$MIRROR/LISTING"
+    if [ ! -f "$listfile" ]
+    then
+        err "list file not found '$listfile'"
+        exit 1
+    fi
     while read -r line
     do
         name="${line%% *}"
         desc="${line#*$name }"
         echo "$(tput bold)$name$(tput sgr0)"
         echo "  $desc"
-    done < "$CM_TMP_PATH/LISTING"
+    done < "$listfile"
 }
 
 if [ "$1" == "help" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
