crapshot: reindent arg parser

diff --git a/crapshot b/crapshot
--- a/crapshot
+++ b/crapshot
@@ -256,60 +256,60 @@ fi
 
 for arg in "$@"
 do
-    if [ "$arg" == "--delete" ]
-    then
-        read_conf
-        delete_history
-        exit 0
-    elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ]
-    then
-        echo "usage: $(basename "$0") [OPTION..]"
-	echo "options:"
-	echo "  --edit"
-	echo "  --select"
-	echo "  --no-browser"
-	echo "  --list"
-	echo "  --delete"
-	echo "  --file <filepath>"
-        echo "description:"
-	echo "  upload screenshots via scp"
-        echo "exmaple:"
-	echo "  $(basename "$0") -s --no-browser"
-        exit 0
-    elif [ "$arg" == "--edit" ] || [ "$arg" == "-e" ]
-    then
-        edit_cnf
-        exit 0
-    elif [ "$arg" == "--list" ]
-    then
-        read_conf
-        list_all
-        exit 0
-    elif [ "$arg" == "--no-browser" ]
-    then
-        arg_no_browser=1
-    elif [ "$arg" == "--file" ]
-    then
-        read_conf
-        arg_is_file=1
-    elif [ "$arg" == "-s" ] || [ "$arg" == "--select" ]
-    then
-        arg_select=1
-    elif [ "${arg::1}" == "-" ]
-    then
-        echo "error: unknown argument '$arg'"
-        echo "       see '$(tput bold)$(basename "$0") --help$(tput sgr0)' for help"
-        exit 1
-    elif [ "$arg_is_file" == "1" ] && [ "$arg_file" == "" ]
-    then
-        arg_file="$arg"
-        if [ ! -f "$arg_file" ]
-        then
-            echo "Error file '$arg_file' not found."
-            exit 1
-        fi
-        cp "$arg_file" "$picpath" || exit 1
-    fi
+	if [ "$arg" == "--delete" ]
+	then
+		read_conf
+		delete_history
+		exit 0
+	elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ]
+	then
+		echo "usage: $(basename "$0") [OPTION..]"
+		echo "options:"
+		echo "  --edit"
+		echo "  --select"
+		echo "  --no-browser"
+		echo "  --list"
+		echo "  --delete"
+		echo "  --file <filepath>"
+		echo "description:"
+		echo "  upload screenshots via scp"
+		echo "exmaple:"
+		echo "  $(basename "$0") -s --no-browser"
+		exit 0
+	elif [ "$arg" == "--edit" ] || [ "$arg" == "-e" ]
+	then
+		edit_cnf
+		exit 0
+	elif [ "$arg" == "--list" ]
+	then
+		read_conf
+		list_all
+		exit 0
+	elif [ "$arg" == "--no-browser" ]
+	then
+		arg_no_browser=1
+	elif [ "$arg" == "--file" ]
+	then
+		read_conf
+		arg_is_file=1
+	elif [ "$arg" == "-s" ] || [ "$arg" == "--select" ]
+	then
+		arg_select=1
+	elif [ "${arg::1}" == "-" ]
+	then
+		echo "error: unknown argument '$arg'"
+		echo "       see '$(tput bold)$(basename "$0") --help$(tput sgr0)' for help"
+		exit 1
+	elif [ "$arg_is_file" == "1" ] && [ "$arg_file" == "" ]
+	then
+		arg_file="$arg"
+		if [ ! -f "$arg_file" ]
+		then
+			echo "Error file '$arg_file' not found."
+			exit 1
+		fi
+		cp "$arg_file" "$picpath" || exit 1
+	fi
 done
 
 if [ "$arg_select" == "1" ]
