Add --file for crapshot

diff --git a/crapshot b/crapshot
--- a/crapshot
+++ b/crapshot
@@ -49,7 +49,7 @@ function check_conf() {
 }
 if [ "$1" == "--help" ]
 then
-    echo "usage: $(basename "$0") [--edit|--select|--no-browser]"
+    echo "usage: $(basename "$0") [--edit|--select|--no-browser|--file <filepath>]"
     echo "description: upload screenshots via scp"
     echo "exmaple: $(basename "$0") -s --no-browser"
     exit 0
@@ -77,7 +77,16 @@ do
     ts="$(date +%s)"
     picname="crapshot_$ts.png"
     picpath="/tmp/$picname"
-    if [ "$1" == "-s" ] || [ "$1" == "--select" ]
+    if [ "$1" == "--file" ]
+    then
+        inputfile="$2"
+        if [ ! -f "$inputfile" ]
+        then
+            echo "Error file '$inputfile' not found."
+            exit 1
+        fi
+        cp "$inputfile" "$picpath" || exit 1
+    elif [ "$1" == "-s" ] || [ "$1" == "--select" ]
     then
         shift
         say "select" &
