crapshot: history and file deletion

diff --git a/crapshot b/crapshot
--- a/crapshot
+++ b/crapshot
@@ -12,6 +12,8 @@
 # chown -R /var/www/html/cs zzh1:zzh1
 conf_dir=~/.config/crools
 conf=~/.config/crools/zzh.cnf
+histfile="$conf_dir/crapshot_history"
+histsize=5
 function os_copy() {
 if [ "$(uname)" == "Darwin" ]
 then
@@ -40,10 +42,12 @@ function check_conf() {
             return
         fi
         mkdir -p $conf_dir
-        echo "# zzh - config" > $conf
-        echo "# store your fav ssh commands here" >> $conf
-        echo "ssh crools@localhost" >> $conf
-        echo "ssh chillerdragon@149.202.127.134" >> $conf
+        {
+            echo "# zzh - config"
+            echo "# store your fav ssh commands here"
+            echo "ssh crools@localhost"
+            echo "ssh chillerdragon@149.202.127.134"
+        } > $conf
         edit_cnf
     fi
 }
@@ -66,6 +70,39 @@ then
     exit 1
 fi
 
+function add_history() {
+    local filename
+    filename="$1"
+    if [ -f "$histfile" ]
+    then
+        tail -n "$((histsize-1))" "$histfile" > "$histfile.tmp" || exit 1
+        mv "$histfile.tmp" "$histfile" || exit 1
+    fi
+    echo "$filename" >> "$histfile"
+}
+
+function delete_history() {
+    if [ ! -f "$histfile" ]
+    then
+        echo "Error there is no history yet"
+        exit 1
+    fi
+    PS3='Pick picture to be deleted (1=latest): '
+    select pic in $(tac "$histfile")
+    do
+        if [ "$pic" == "" ]
+        then
+            echo "invalid option"
+        else
+            echo "deleting '$pic' ..."
+            cmd="ssh $remote \"rm -f $pic\""
+            echo "$cmd"
+            eval "$cmd"
+            exit 0
+        fi
+    done
+}
+
 while IFS= read -r line
 do
     if [ "${line:0:1}" == "#" ]
@@ -77,43 +114,49 @@ do
     ts="$(date +%s)"
     picname="crapshot_$ts.png"
     picpath="/tmp/$picname"
-    if [ "$1" == "--file" ]
-    then
-        inputfile="$2"
-        if [ ! -f "$inputfile" ]
-        then
-            echo "Error file '$inputfile' not found."
-            exit 1
-        fi
-        cp "$inputfile" "$picpath" || exit 1
-    elif [ "$1" == "-s" ] || [ "$1" == "--select" ]
-    then
-        shift
-        say "select" &
-        maim -s "$picpath"
-    else
-        maim "$picpath"
-    fi
-    say crapshot
-    cmd="scp $picpath $remote:/var/www/html/cs/.$ts.png"
-    echo "$cmd"
-    eval "$cmd"
-    url="https://$host/cs/.$ts.png"
-    echo "$url"
-    os_copy "$url"
-    if [ "$1" == "--no-browser" ]
-    then
-        exit 0
-    fi
-    if [ "$BROWSER" != "" ]
-    then
-        $BROWSER "$url" &
-    elif [ "$(uname)" == "Darwin" ]
-    then
-        open -a Safari "$url"
-    else
-        firefox "$url" &
-    fi
-    exit 0
+    break
 done < $conf
+
+if [ "$1" == "--delete" ]
+then
+    delete_history
+    exit 0
+elif [ "$1" == "--file" ]
+then
+    inputfile="$2"
+    if [ ! -f "$inputfile" ]
+    then
+        echo "Error file '$inputfile' not found."
+        exit 1
+    fi
+    cp "$inputfile" "$picpath" || exit 1
+elif [ "$1" == "-s" ] || [ "$1" == "--select" ]
+then
+    shift
+    say "select" &
+    maim -s "$picpath"
+else
+    maim "$picpath"
+fi
+say crapshot
+cmd="scp $picpath $remote:/var/www/html/cs/.$ts.png"
+echo "$cmd"
+eval "$cmd"
+add_history "/var/www/html/cs/.$ts.png"
+url="https://$host/cs/.$ts.png"
+echo "$url"
+os_copy "$url"
+if [ "$1" == "--no-browser" ]
+then
+    exit 0
+fi
+if [ "$BROWSER" != "" ]
+then
+    $BROWSER "$url" &
+elif [ "$(uname)" == "Darwin" ]
+then
+    open -a Safari "$url"
+else
+    firefox "$url" &
+fi
 
