crapshot: dependency improvement

diff --git a/crapshot b/crapshot
--- a/crapshot
+++ b/crapshot
@@ -15,13 +15,77 @@ conf=~/.config/crools/zzh.cnf
 picdir=/var/www/html/cs
 histfile="$conf_dir/crapshot_history"
 histsize=5
+
+function is_arch() {
+    if [ -f /etc/arch-release ] && uname -r | grep -q arch
+    then
+        return 0
+    fi
+    return 1
+}
+function is_apple() {
+    if [[ "$OSTYPE" == "darwin"* ]]
+    then
+        return 0
+    fi
+    return 1
+}
+function install_tool() {
+    local tool
+    local pckmn
+    tool="$1"
+    if [ -x "$(command -v "$1")" ]
+    then
+        return
+    fi
+    if is_apple
+    then
+        brew install "$tool" || exit 1
+    else
+        if is_arch
+        then
+            pckmn="pacman -Sy"
+        else
+            pckmn="apt install"
+        fi
+        if [ "$UID" == "0" ]
+        then
+            eval "$pckmn $tool" || exit 1
+        else
+            if [ -x "$(command -v sudo)" ]
+            then
+                eval "sudo $pckmn $tool" || exit 1
+            else
+                echo "[!] Error: install sudo"
+                exit 1
+            fi
+        fi
+    fi
+}
 function os_copy() {
-if [ "$(uname)" == "Darwin" ]
-then
-    echo "$1" | pbcopy
-else
-    echo "$1" | xsel -ib
-fi
+    if is_apple
+    then
+        echo "$1" | pbcopy
+    else
+        echo "$1" | xsel -ib
+    fi
+}
+function os_say() {
+    if [ -x "$(command -v say)" ]
+    then
+        say "$1"
+    elif [ -x "$(command -v espeak)" ]
+    then
+        espeak "$1"
+    elif [ -x "$(command -v spd-say)" ]
+    then
+        spd-say "$1"
+    elif [ -x "$(command -v festival)" ]
+    then
+        echo "$1" | festival --tts
+    else
+        echo "Error: no text to speech tool found"
+    fi
 }
 function edit_cnf() {
     if [ ! -f $conf ]
@@ -52,6 +116,7 @@ function check_conf() {
         edit_cnf
     fi
 }
+install_tool maim
 if [ "$1" == "--help" ] || [ "$1" == "-h" ]
 then
     echo "usage: $(basename "$0") [--edit|--select|--no-browser|--list|--file <filepath>]"
@@ -175,10 +240,10 @@ then
 elif [ "$1" == "-s" ] || [ "$1" == "--select" ]
 then
     shift
-    say "select" &
+    os_say "select" &
     if ! maim -s "$picpath"
     then
-        say "abort"
+        os_say "abort"
         echo "crapshot aborted."
         exit 1
     fi
@@ -191,7 +256,7 @@ else
     fi
 fi
 os_copy "crapshot in progress"
-say crapshot
+os_say crapshot
 cmd="scp $picpath $remote:$picdir/.$ts.png"
 echo "$cmd"
 eval "$cmd"
