crasswd: pass dependency and bash autocompletion

diff --git a/crasswd b/crasswd
--- a/crasswd
+++ b/crasswd
@@ -1,20 +1,85 @@
 #!/bin/bash
 # crasswd: wrapper for the unix password manager pass
-if [ "$#" != "1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
-then
-    echo "USAGE: $(basename "$0") <password>"
-    echo "DESCRIPTION: copies the last line"
-    echo "  of the password stored by pass"
-    echo "  into system copy buffer"
-    echo "  the buffer will clear after 45 sec"
-    echo "USE CASE: multi line pass entrys"
-    echo "  starting with name/mail and ending"
-    echo "  with the password"
-    echo "EXAMPLE:"
-    echo "  $(tput bold)$(basename "$0") path/to/pw$(tput sgr0)"
-    echo "  executes 'pass show path/to/pw | tail -n1 | xsel -ib'"
-    exit 0
-fi
+function help_page() {
+    if [ "$#" != "1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
+    then
+        echo "USAGE: $(basename "$0") <password>"
+        echo "DESCRIPTION: copies the last line"
+        echo "  of the password stored by pass"
+        echo "  into system copy buffer"
+        echo "  the buffer will clear after 45 sec"
+        echo "USE CASE: multi line pass entrys"
+        echo "  starting with name/mail and ending"
+        echo "  with the password"
+        echo "EXAMPLE:"
+        echo "  $(tput bold)$(basename "$0") path/to/pw$(tput sgr0)"
+        echo "  executes 'pass show path/to/pw | tail -n1 | xsel -ib'"
+        exit 0
+    fi
+}
+
+function is_arch() {
+    if [ -f /etc/arch-release ] && uname -r | grep -q arch
+    then
+        return 0
+    fi
+    return 1
+}
+
+function is_apple() {
+    if [[ "$OSTYPE" == "darwin"* ]]
+    then
+        return 0
+    fi
+    return 1
+}
+
+function install_tool() {
+    local tool
+    local pckmn
+    tool="$1"
+    if is_apple
+    then
+        brew install "$tool"
+    else
+        if is_arch
+        then
+            pckmn="pacman -Sy"
+        else
+            pckmn="apt install"
+        fi
+        if [ "$UID" == "0" ]
+        then
+            eval "$pckmn $tool"
+        else
+            if [ -x "$(command -v sudo)" ]
+            then
+                eval "sudo $pckmn $tool"
+            else
+                echo "[!] Error: install sudo"
+                exit 1
+            fi
+        fi
+    fi
+}
+
+function install_bash_completion() {
+    if [ -f /usr/share/bash-completion/completions/crasswd ]
+    then
+        return
+    fi
+    if [ ! -x "$(command -v pass)" ]
+    then
+        install_tool pass
+    fi
+    if [ ! -f /usr/share/bash-completion/completions/pass ]
+    then
+        return
+    fi
+    sed 's/complete -o filenames -F _pass pass/complete -o filenames -F _pass crasswd/' \
+        /usr/share/bash-completion/completions/pass > /tmp/crools_crasswd_completion
+    sudo mv /tmp/crools_crasswd_completion /usr/share/bash-completion/completions/crasswd
+}
 
 function os_copy() {
     if [ "$(uname)" == "Darwin" ]
@@ -30,6 +95,8 @@ function clear_buffer() {
     os_copy ""
 }
 
+install_bash_completion
+help_page
 os_copy "$(pass show "$1" | tail -n1)"
 clear_buffer &
 
