crepl: autocomplete c++ keywords

diff --git a/crepl b/crepl
--- a/crepl
+++ b/crepl
@@ -7,13 +7,13 @@
 
 COL_RESET=''
 COL_BLACK=''
-COL_RED=''
-COL_GREEN=''
+# COL_RED=''
+# COL_GREEN=''
 COL_YELLOW=''
 COL_BLUE=''
-COL_MAGENTA=''
-COL_CYAN=''
-COL_WHITE=''
+# COL_MAGENTA=''
+# COL_CYAN=''
+# COL_WHITE=''
 
 init_colors() {
 	# https://no-color.org/
@@ -28,23 +28,23 @@ init_colors() {
 	then
 		COL_RESET="\e[0m"
 		COL_BLACK="\e[0;30m";
-		COL_RED="\e[0;31m";
-		COL_GREEN="\e[0;32m";
+		# COL_RED="\e[0;31m";
+		# COL_GREEN="\e[0;32m";
 		COL_YELLOW="\e[0;33m";
 		COL_BLUE="\e[0;34m";
-		COL_MAGENTA="\e[0;35m";
-		COL_CYAN="\e[0;36m";
-		COL_WHITE="\e[0;37m";
+		# COL_MAGENTA="\e[0;35m";
+		# COL_CYAN="\e[0;36m";
+		# COL_WHITE="\e[0;37m";
 
 		# bold
-		COL_BBLACK="\e[1;30m";
-		COL_BRED="\e[1;31m";
-		COL_BGREEN="\e[1;32m";
-		COL_BYELLOW="\e[1;33m";
-		COL_BBLUE="\e[1;34m";
-		COL_BMAGENTA="\e[1;35m";
-		COL_BCYAN="\e[1;36m";
-		COL_BWHITE="\e[1;37m";
+		# COL_BBLACK="\e[1;30m";
+		# COL_BRED="\e[1;31m";
+		# COL_BGREEN="\e[1;32m";
+		# COL_BYELLOW="\e[1;33m";
+		# COL_BBLUE="\e[1;34m";
+		# COL_BMAGENTA="\e[1;35m";
+		# COL_BCYAN="\e[1;36m";
+		# COL_BWHITE="\e[1;37m";
 	else
 		printf 'Warning: your system does not seem to support colors'
 	fi
@@ -60,6 +60,24 @@ dbg() {
 log() {
 	printf '[*] %s\n' "$1"
 }
+err() {
+	printf '[-] %s\n' "$1"
+}
+
+if [ "${BASH_VERSINFO[0]}" -lt 5 ] && [ "${BASH_VERSINFO[1]}" -lt 3 ]
+then
+	err "Error: you need at least bash 4.2 the blaze it edition"
+	err "       because this script uses negative indecies in arrays"
+	exit 1
+fi
+if [ "${BASH_VERSINFO[0]}" -lt 5 ] && [ "${BASH_VERSINFO[1]}" -lt 5 ]
+then
+	err "Error: you need at least bash 4.4"
+	err "       because this script uses mapfile -t array < <(mycommand)"
+	err "       https://www.shellcheck.net/wiki/SC2207"
+	exit 1
+fi
+
 
 # if the user input does not end with semicolon
 # append one so it compiles correctly
@@ -163,14 +181,53 @@ fmt_int_value() {
 	fi
 }
 
+# takes in the full prompt
+# and prints only the last word
+# that should be used for auto completion
+# for example:
+# 	in:  unsigned int a 2;pr
+# 	out: pr
+line_to_autocomplete_word() {
+	local line="$1"
+	local tokens
+	IFS=')(",; ' read -ra tokens <<< "$line"
+	printf '%s' "${tokens[-1]}"
+}
+
 tab_complete() {
 	# p<tab> works but this is ugly use compgen to generate that stuff
 	[[ ${#READLINE_LINE} -eq 0 ]] && READLINE_LINE=$(fc -l -n -1 | xargs)
-	if [ "$READLINE_LINE" == "p" ]
-	then
-		READLINE_LINE="printf("
-		READLINE_POINT="${#READLINE_LINE}"
-	fi
+
+	# "do" has to be qouted to calm shellcheck
+	# https://github.com/koalaman/shellcheck/issues/2931
+	local cpp_keywords=(
+		alignas alignof and and_eq asm atomic_cancel atomic_commit atomic_noexcept
+		auto bitand bitor bool break case catch char char8_t char16_t char32_t
+		class compl concept const consteval constexpr constinit const_cast continue
+		co_await co_return co_yield decltype default delete "do" double dynamic_cast else
+		enum explicit export extern false float for friend goto if inline int long mutable
+		namespace new noexcept not not_eq nullptr operator or or_eq private protected public
+		reflexpr register reinterpret_cast requires return short signed sizeof static
+		static_assert static_cast struct switch template this throw true try typedef
+		typeid typename union unsigned virtual void volatile wchar_t while
+	)
+	local word_to_complete
+	word_to_complete="$(line_to_autocomplete_word "$READLINE_LINE")"
+	[ "$word_to_complete" = "" ] && return
+
+	local completions
+	# we set IFS= for the read call we currently are in
+	# so we have to enable IFS word splitting again for compgen to work
+	mapfile -t completions < <(IFS=$' \t\n' compgen -W "$(printf "'%s' " "${cpp_keywords[@]}")" -- "$word_to_complete")
+	[ "${#completions[@]}" -eq 0 ] && return
+
+	local wanted_word="${completions[0]}"
+	local current_word_len="${#word_to_complete}"
+	local append_str
+	append_str="${wanted_word:$current_word_len}"
+
+	READLINE_LINE+="$append_str"
+	READLINE_POINT="${#READLINE_LINE}"
 }
 
 mkdir -p ~/.config/crools
@@ -320,4 +377,3 @@ do
 done
 
 history -w ~/.config/crools/crepl_history
-
