crools: shellfunc all_dirs

diff --git a/crools b/crools
--- a/crools
+++ b/crools
@@ -77,14 +77,40 @@ then
     fi
 fi
 
-if ! is_func whereami && ! grep -q whereami "$shellrc"
-then
-    echo "[*] installing shell functions ..."
-    echo '
-whereami() {
-    echo -e "STY: \033[0;31m$STY\033[0m"
-    ps wwf -s $$
-}
-' >> "$shellrc"
+function install_shellfunc() {
+    local name="$1"
+    local code="$2"
+    if ! is_func "$name" && ! grep -q "$name" "$shellrc"
+    then
+        echo "[*] installing shell function '$name' ..."
+        echo -e "\\n$code\\n" >> "$shellrc"
 fi
+}
+
+# shellcheck disable=SC2016
+install_shellfunc whereami \
+'whereami() {
+    echo -e "STY: \\\\033[0;31m$STY\\\\033[0m"
+    ps wwf -s $$
+}'
+
+# shellcheck disable=SC2016
+install_shellfunc all_dirs \
+'function all_dirs() {
+    if [ "$#" == "0" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$1" == "help" ]
+    then
+        echo "usage: all_dirs [SHELLCOMMANDS...]"
+        echo "navigates to every folder in current directory"
+        echo "and evals all given arguments there"
+        return
+    fi
+    cwd="$(pwd)";
+    for d in ./*/;
+    do
+        echo -e "\\\\n$(tput bold)$d$(tput sgr0)\\\\n";
+        cd "$d" || { echo "Error: $d failed"; return; }
+        eval "$*";
+        cd "$cwd" || { echo "Error: navigating back to $cwd failed"; return; }
+    done;
+}'
 
