crools: update dotfiles if found

diff --git a/crools b/crools
--- a/crools
+++ b/crools
@@ -1,12 +1,14 @@
 #!/bin/bash
 
 function git_save_pull() {
+    local repo
+    repo=${1:-crools}
     if [ "$(git status | tail -n1)" != "nothing to commit, working tree clean" ]
     then
-        echo "WARNING: git pull failed! Is your crools working tree clean?"
+        echo "WARNING: git pull failed! Is your $repo working tree clean?"
         return
     fi
-	echo "[*] updating crools ..."
+	echo "[*] updating $repo ..."
     git pull
 }
 
@@ -25,5 +27,15 @@ then
     exec "$SHELL"
 else
     git_save_pull
+fi
+
+if [ -d ../dotfiles ] && [ -f ../dotfiles/setup.sh ]
+then
+    cd ../dotfiles || exit 1
+    if git remote -v | grep -q '^origin.*ChillerDragon/dotfiles '
+    then
+        git_save_pull dotfiles
+        ./setup.sh
+    fi
 fi
 
