gg: I use darwinOS btw

diff --git a/gg b/gg
--- a/gg
+++ b/gg
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 cat << 'LOGO'
        _ _                 _   
@@ -30,6 +30,14 @@ readonly reset="\e[0m"
 readonly WHITE="\e[1;37m"
 
 
+if [[ "${BASH_VERSINFO[0]}" -lt 5 ]]
+then
+	# for example the ${arg,,}
+	# throws bad substitution error for bash 3 which is default on macOS
+	echo "Error: your bash version ${BASH_VERSINFO[0]} is too old"
+	echo "       you need at least bash 5 to run this script"
+	exit 1
+fi
 
 function usage() {
 	echo "usage: gg <repo>"
