tw_cmake: add ddnet support

diff --git a/tw_cmake b/tw_cmake
--- a/tw_cmake
+++ b/tw_cmake
@@ -2,43 +2,54 @@
 #
 # tw_cmake - https://github.com/ChillerDragon/crools/blob/master/tw_cmake
 #
-# tool to generate CMakeLists.txt for teeworlds
+# tool to generate CMakeLists.txt for teeworlds and ddnet
 # only datasrc directory tho
 # it looks at the datasrc directory inserts the sorted list
 # in CMakeLists.txt
 #
 # USAGE
-# navigate to the root of the teeworlds repository
+# navigate to the root of the teeworlds or ddnet repository
 # and then execute:
 # tw_cmake .
 
 if [ "$#" -ne "1" ]
 then
-    echo "Usage: $(basename "$0") <teeworlds path>"
+    echo "Usage: $(basename "$0") <teeworlds source root>"
     exit 1
 fi
 twpath="$1"
 cmakelist="$twpath/"CMakeLists.txt
 datasrc_path="$twpath/datasrc"
 
+if [ ! -f "$cmakelist" ]
+then
+    echo "[-] Error: '$cmakelist' file not found."
+    exit 1
+fi
+if [ ! -f "$datasrc_path"/game.png ] && [ -f "$twpath"/data/game.png ]
+then
+    datasrc_path="$twpath/data"
+    echo "[*] use data/ dir instead of datasrc/"
+fi
 if [ ! -d "$datasrc_path" ]
 then
-    echo "Error: '$datasrc_path' path not found."
-    exit 1
-elif [ ! -f "$cmakelist" ]
-then
-    echo "Error: '$cmakelist' file not found."
+    echo "[-] Error: '$datasrc_path' path not found."
     exit 1
 fi
 
 files=$(find "$datasrc_path" -type f \( \
     -name "*.json" -o \
+    -name "*.rules" -o \
     -name "*.png" -o \
     -name "*.wv" -o \
     -name "*.txt" -o \
     -name "*.ttf" -o \
+    -name "*.otf" -o \
+    -name "*.frag" -o \
+    -name "*.vert" -o \
     -name "*.map" \) -print0 | while IFS= read -r -d '' f
 do
+    f="${f// /\\ }"
     echo "  ${f/$datasrc_path\//}"
 done | LC_ALL=C sort)
 
@@ -55,4 +66,6 @@ empty=$(sed '/set(EXPECTED_DATA/,/)/d' "$cmakelist" | \
     printf ")"
     echo "$empty" | sed -n -e '1,/XXX END/!p'
 } > "$cmakelist"
+
+echo "[*] done"
 
