Make tw_cmake super user friendly

diff --git a/tw_cmake b/tw_cmake
--- a/tw_cmake
+++ b/tw_cmake
@@ -1,15 +1,37 @@
 #!/bin/bash
+#
+# tw_cmake - https://github.com/ChillerDragon/crools/blob/master/tw_cmake
+#
 # tool to generate CMakeLists.txt for teeworlds
 # only datasrc directory tho
+# it looks at the datasrc directory inserts the sorted list
+# in CMakeLists.txt
+#
+# USAGE
+# navigate to the root of the teeworlds repository
+# and then execute:
+# tw_cmake .
 
 if [ "$#" -ne "1" ]
 then
-    echo "Usage: $(basename "$0") <datasrc path>"
+    echo "Usage: $(basename "$0") <teeworlds path>"
     exit 1
 fi
-datasrc_path=$1
+twpath="$1"
+cmakelist="$twpath/"CMakeLists.txt
+datasrc_path="$twpath/datasrc"
 
-find "$datasrc_path" -type f \( \
+if [ ! -d "$datasrc_path" ]
+then
+    echo "Error: '$datasrc_path' path not found."
+    exit 1
+elif [ ! -f "$cmakelist" ]
+then
+    echo "Error: '$cmakelist' file not found."
+    exit 1
+fi
+
+files=$(find "$datasrc_path" -type f \( \
     -name "*.json" -o \
     -name "*.png" -o \
     -name "*.wv" -o \
@@ -17,6 +39,20 @@ find "$datasrc_path" -type f \( \
     -name "*.ttf" -o \
     -name "*.map" \) -print0 | while IFS= read -r -d '' f
 do
-    echo "  ${f/$datasrc_path/}"
-done | LC_ALL=C sort | xsel -ib
+    echo "  ${f/$datasrc_path\//}"
+done | LC_ALL=C sort)
+
+pad="########################################################################"
+empty=$(sed '/set(EXPECTED_DATA/,/)/d' "$cmakelist" | \
+    tr '\n' '\f' | \
+    sed -e "s/# DATA\\f$pad/# DATA\\f$pad\\fXXX START\\fXXX END/" | \
+    tr '\f' '\n')
+{
+    echo "$empty" | sed -n -e '/XXX START/,$!p'
+    echo ""
+    echo "set(EXPECTED_DATA"
+    echo "$files"
+    printf ")"
+    echo "$empty" | sed -n -e '1,/XXX END/!p'
+} > "$cmakelist"
 
