crackman: arch support

diff --git a/packages/luarocks-src b/packages/luarocks-src
--- a/packages/luarocks-src
+++ b/packages/luarocks-src
@@ -37,14 +37,18 @@ then
 	fi
 else
 	distro="$(grep "^ID=" /etc/os-release | cut -d'=' -f2)"
-	if [ "$distro" != "debian" ]
-	then
-		echo "Error: luarocks is only supported on debian"
-		exit 1
-	fi
 	if [ ! -x "$(command -v fzf)" ]
 	then
-		sudo apt-get install -y fzf || exit 1
+		if [ "$distro" = "debian" ]
+		then
+			sudo apt-get install -y fzf || exit 1
+		elif [ "$distro" = "arch" ]
+		then
+			sudo pacman -Sy fzf || exit 1
+		else
+			echo "Error: luarocks is not supported on '$distro'"
+			exit 1
+		fi
 	fi
 
 	cd "$CM_SRC_PATH" || exit 1
